### PR TITLE
Add clarification around how group and check configurations interact

### PR DESCRIPTION
**Pull request by cjanslow**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

### CODE REVIEW

**Review by ragog — COMMENTED** [review]
@cjanslow do we want to make this callout even more explicit? i.e. adding a bit saying smth along the lines of "This means a check within a group with no connected alert channels _will not alert_."

Otherwise LGTM already

**Comment by cjanslow** [comment]
@ragog Great thought, I made that change as well. Please re-review when you get a chance.

**Comment by ragog** [comment]
@cjanslow I highlighted the warnings on both pages in a bit of a different way. Later we might want to take another look at the Groups page in general as it is not CLI-first, but that's a different PR. Could you review?

**Comment by cjanslow** [comment]
@ragog These changes look great, makes the impact a lot more obvious! LGTM

**Review by ragog — APPROVED** [review]
LGTM

**Pull request merged**
