### PR TITLE
K8s section

### PR DESCRIPTION
**Pull request by serverless-mom**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [ ] Docs
* [x] Learn
* [ ] Other

### CODE REVIEW

**Comment by serverless-mom** [comment]
I did a drive-by here renaming the otel logo's .svg to be a little more consistent.

**Review by tnolet — COMMENTED** [review]
The menu structure and breadcrumbs are incorrect now. 

- For some reason the PWT section has multiple top level items with icons, the rest doesn't.
- The K8S section has no base breadcrumb

CleanShot 2024-12-02 at 16 56 18@2x

**Comment by serverless-mom** [comment]
Working on a fix, converting to draft since this isn't ready to merge

**Review by tnolet — CHANGES_REQUESTED** [review]
The OTEL icon is broken 
CleanShot 2024-12-02 at 17 10 22@2x

**Comment by serverless-mom** [comment]
Screenshot 2024-12-02 at 10 12 08 AM
lefthand toolbar and top breadcrumbs are now fixed

**Comment by tnolet** [comment]
> Per slack discussion we may be reorganizing these menus, I think we can merge this branch with main in the interim @Dgiordano33

I agree, let's merge this so I have a clean slate to work from

**Pull request merged**
