### PR TITLE
fix: clean up reported 404s in google search console

### PR DESCRIPTION
**Pull request by stefanjudis**
## Affected Components
* [x] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer

Just adding some more redirects to clean up Google search console errors.

### CODE REVIEW

**Review by tnolet — DISMISSED** [review]
LGTM

**Comment by stefanjudis** [comment]
Sorry Tim, you were too fast. I'll watch out to not ping you prematurely going forward. :)

**Review by tnolet — APPROVED** [review]
LGTM

**Comment by stefanjudis** [comment]
@tnolet Okay... with our redirect / tunnelling setup this somehow breaks. 

image

I'll revert this prod deployment and investigate after lunch.

**Pull request merged**
