### PR TITLE
update images for adding team members

### PR DESCRIPTION
**Pull request by Dnhem**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [X] Docs
* [ ] Learn
* [ ] Other

### CODE REVIEW

**Comment by checklyalex** [comment]
Can we remove "support view" on the left hand side from the screenshots?  @Dnhem

**Comment by Dnhem** [comment]
> Can we remove "support view" on the left hand side from the screenshots? @Dnhem

Good call, done ✅

**Review by ragog — COMMENTED** [review]
LGTM @Dnhem

**Review by ragog — APPROVED** [review]
@Dnhem LGTM

**Pull request merged**
