### PR TITLE
feat: restructures all learn content into three menus. Adds new gener…

### PR DESCRIPTION
**Pull request by tnolet**
…ic menu structure. adds index pages for pwt and k8s sections [sc-00]

## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [x] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer
- adds each learn section (pwt, otel and k8s) to its own menu ID, e.g. `learn_playwright` and `learn_opentelemetry`
- adds a global index page for "learn".
- adds dedicated index pages for each section.
- introduces new partials for rendering the menus. New menus for new section are now simpler to create.

The URL structure has not changed.

Note: we need to make the copy and style of the new index pages maybe a bit better. It's bare bones now.

## Screenshots

See the preview deployment.

### CODE REVIEW

**Comment by Dgiordano33** [comment]
This looks great! 

We do need a breadcrumb set up that flows from the top-level Topic page back to the "Learn" section. 

Maybe near these arrows?
image

**Comment by tnolet** [comment]
@Dgiordano33 would something like this be enough? 
CleanShot 2024-12-09 at 14 37 49@2x

**Comment by tnolet** [comment]
@Dgiordano33 ok, done https://checklyhq-com-git-tnolet-new-learn-structure-sc00-checkly.vercel.app/learn/opentelemetry/getting-started-with-observability/

**Review by Dgiordano33 — APPROVED** [review]
LGTM

**Pull request merged**
