### PR TITLE
feat: add ToC on the guides section

### PR DESCRIPTION
**Pull request by pilimartinez**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [ ] Docs
* [ ] Learn
* [X] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer

Add ToC on guides section 

## Screenshots

image

### CODE REVIEW

**Comment by stefanjudis** [comment]
@pilimartinez There's a container missing that limits the overall width. 🫣

image

**Comment by pilimartinez** [comment]
> @pilimartinez There's a container missing that limits the overall width. 🫣
> 
> image

Should be fixed now 👍

**Review by stefanjudis — CHANGES_REQUESTED** [review]
Could we have the same "sticky" behavior we have in the docs? 

image

In the docs the TOC tables sticks on the top when scrolling?

**Review by stefanjudis — CHANGES_REQUESTED** [review]
Hmm, that looks like different behavior. Could we have the same sidebar behavior?


https://github.com/checkly/docs.checklyhq.com/assets/962099/409a280c-74e5-406c-8bc3-9907c8c6b035

Happy to wrangle it together and help. :)

**Review by stefanjudis — APPROVED** [review]

**Pull request merged**
