### PR TITLE
feat: apply changes / fixes from docs to learn [sc-00]

### PR DESCRIPTION
**Pull request by tnolet**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [ ] Docs
* [x] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer
- ports over best nav fixes and best practices from docs section.
- cleans up the list page

### CODE REVIEW

**Review by serverless-mom — DISMISSED** [review]
Renders well, works with new Otel content, maintains URL structure, looks g2g

**Comment by Dgiordano33** [comment]
Feels like we moved backwards in styling? How come we added these dropdown carets instead of the icons?

**Comment by tnolet** [comment]
> Feels like we moved backwards in styling? How come we added these dropdown carets instead of the icons?

@Dgiordano33 I disagree. The icons added nothing but visual noise. Also they had no relation to the topic. The page is much more inline with "best in class" docs I see from other SaaS vendors. This is cleaner and optimizes for a good reading  experience.

We could add icons if they have a clear purpose and match the topic.

**Comment by Dgiordano33** [comment]
This isn't a docs section. This is the learn section and supposed to be different. 

I will add them back, thanks!

**Pull request merged**
