### PR TITLE
More otel content

### PR DESCRIPTION
**Pull request by serverless-mom**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [ ] Docs
* [x] Learn
* [ ] Other

A few beginner pieces of content, could use more graphics but otherwise ready for review.

### CODE REVIEW

**Comment by serverless-mom** [comment]
oh and uh... I fixed the headings in [/guides/empowering-developers-with-checkly.md](https://github.com/checkly/docs.checklyhq.com/pull/1108/files#diff-6e1feb959be70dc5ce9afe34c997a741870baba8e4b6eebf091953ac93a34f34) which... total driveby sorry.

**Comment by Dgiordano33** [comment]
What's the status of this? Are we ready to push?

"A few beginner pieces of content, known issues:

not perfectly SEO optimized
no links to blog content
some of this was written directly into VSCode, and so it needs a spelling/grammar scan
too many links to opentelemetry.io. As our own Otel content grows, this will improve
possibly a broken link here or there to /learn/opentelemetry/otel-logs which will be resolved as the initial 10-12 pieces of content are all PR'ed
"

Is the spelling checked at least?

**Comment by serverless-mom** [comment]
Will ready to push by EOD today, will flag future PR’s if they’re not ready
to merge.

**Comment by serverless-mom** [comment]
This is now ready for review, has received:

* spelling lint
* links connected

**Pull request merged**
