### PR TITLE
many small SEO tweaks, and added the displayTitle param to docs pages…

### PR DESCRIPTION
**Pull request by serverless-mom**
… with accompanying updates to layouts

## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [x] Code is linted (`npm run lint`)

*note:* I haven't deleted `metatags: title` from every article, as it's doing no harm it's just adding an OpenGraph tag.

### CODE REVIEW

**Comment by drakirnosslin** [comment]
I'm not a huge fan of these long titles for the documentation pages, it makes it hard to quickly find what I'm looking for in the navigation. When looking at the sidebar, it's feels messy and is hard to read because the line length is so limited:

CleanShot 2024-07-18 at 09 09 01

and

CleanShot 2024-07-18 at 09 09 54

Also, since the titles no longer begin with the name of what I'm integrating, I need to scan a lot more text before I find what I search for. This makes it much easier for someone to miss what we offer when they scan the sidebar.

Can we limit the changes to the metadata + guides/learn article naming? Or come up with shorter names that still work for SEO?

**Comment by serverless-mom** [comment]
Oh, these are not supposed to be showing up like this, I’ll fix it, and
make sure it’s just the display title that shows up here.

**Comment by drakirnosslin** [comment]
Super, thank you! 🙏 

> Oh, these are not supposed to be showing up like this, I’ll fix it, and make sure it’s just the display title that shows up here. Sent from a phone

**Comment by serverless-mom** [comment]
Screenshot 2024-07-18 at 7 12 04 AM
@drakirnosslin Sorry for the confusion, this is fixed now that I merged the recently merged updates from main

**Comment by drakirnosslin** [comment]
No problem, this is why we have PRs 😄 

>  @drakirnosslin Sorry for the confusion, this is fixed now that I merged the recently merged updates from main

**Review by drakirnosslin — APPROVED** [review]

**Pull request merged**
